AWSTemplateFormatVersion: 2010-09-09
Description: |
   This template launched an EC2 that enables SSH
Resources:
    MyEc2:
      Type: AWS::EC2::Instance
      Properties:
        ImageId: ami-0ab4d1e9cf9a1215a
        InstanceType: t2.micro
        KeyName: ec2_key
        SecurityGroups:
          - cfn-demo-secgrp
        Tags:
          - Key: Name 
            Value: busra-cf-stack-instance


  
            


  
