AWSTemplateFormatVersion: 2010-09-09
Description: |
  Aws CloudFormation Demo
Resources:
  AwsDemo:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-09e67e426f25ce0d7
      InstanceType: t2.micro
      KeyName: ec2_key
      SecurityGroups:
        - instance-scr
      Tags:
        - Key : Name
          Value : Aws-Demo